// Generated by generateTools.ts
import { McpToolDefinition } from './types.js';

export const toolDefinitionMap = new Map<string, McpToolDefinition>([
  ["text-to-object-detection", {
  "name": "text-to-object-detection",
  "description": "Tool Text To Od",
  "inputSchema": {
    "type": "object",
    "properties": {
      "timeout": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "default": 480,
        "title": "Timeout"
      },
      "Authorization": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "Use your API key as a Basic token. For example, `Authorization = Basic YOUR_API_KEY`.\n\nTo get your API key, go to https://va.landing.ai/settings/api-key.",
        "title": "Authorization"
      },
      "authorization": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "title": "Authorization"
      },
      "requestBody": {
        "properties": {
          "image": {
            "anyOf": [
              {
                "type": "string",
                "format": "binary"
              },
              {
                "type": "null"
              }
            ],
            "title": "Image"
          },
          "video": {
            "anyOf": [
              {
                "type": "string",
                "format": "binary"
              },
              {
                "type": "null"
              }
            ],
            "title": "Video"
          },
          "prompts": {
            "items": {
              "type": "string"
            },
            "type": "array",
            "minItems": 1,
            "title": "Prompts"
          },
          "model": {
            "type": "string",
            "enum": [
              "owlv2",
              "countgd",
              "florence2",
              "agentic",
              "glee",
              "florencev2"
            ],
            "title": "TextToODModel"
          },
          "nmsThreshold": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "title": "Nmsthreshold"
          },
          "confidence": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "title": "Confidence"
          },
          "jobId": {
            "anyOf": [
              {
                "type": "string",
                "format": "uuid"
              },
              {
                "type": "null"
              }
            ],
            "title": "Jobid"
          }
        },
        "type": "object",
        "required": [
          "prompts",
          "model"
        ],
        "title": "FormData",
        "description": "Request body (content type: application/x-www-form-urlencoded)"
      }
    },
    "required": [
      "requestBody"
    ]
  },
  "method": "post",
  "pathTemplate": "/v1/tools/text-to-object-detection",
  "parameters": [
    {
      "name": "timeout",
      "in": "query",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "default": 480,
        "title": "Timeout"
      }
    },
    {
      "name": "Authorization",
      "in": "header",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "Use your API key as a Basic token. For example, `Authorization = Basic YOUR_API_KEY`.\n\nTo get your API key, go to https://va.landing.ai/settings/api-key.",
        "title": "Authorization"
      },
      "description": "Use your API key as a Basic token. For example, `Authorization = Basic YOUR_API_KEY`.\n\nTo get your API key, go to https://va.landing.ai/settings/api-key."
    },
    {
      "name": "authorization",
      "in": "header",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "title": "Authorization"
      }
    }
  ],
  "executionParameters": [
    {
      "name": "timeout",
      "in": "query"
    },
    {
      "name": "Authorization",
      "in": "header"
    },
    {
      "name": "authorization",
      "in": "header"
    }
  ],
  "requestBodyContentType": "application/x-www-form-urlencoded",
  "securityRequirements": [],
  "baseUrl": "https://api.va.landing.ai"
}],
  ["depth-pro", {
  "name": "depth-pro",
  "description": "Tool Depth Pro",
  "inputSchema": {
    "type": "object",
    "properties": {
      "timeout": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "default": 480,
        "title": "Timeout"
      },
      "Authorization": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "Use your API key as a Basic token. For example, `Authorization = Basic YOUR_API_KEY`.\n\nTo get your API key, go to https://va.landing.ai/settings/api-key.",
        "title": "Authorization"
      },
      "authorization": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "title": "Authorization"
      },
      "requestBody": {
        "properties": {
          "image": {
            "anyOf": [
              {
                "type": "string",
                "format": "binary"
              },
              {
                "type": "null"
              }
            ],
            "title": "Image"
          },
          "video": {
            "anyOf": [
              {
                "type": "string",
                "format": "binary"
              },
              {
                "type": "null"
              }
            ],
            "title": "Video"
          }
        },
        "type": "object",
        "title": "BaseMediaRequest",
        "description": "Request body (content type: application/x-www-form-urlencoded)"
      }
    },
    "required": [
      "requestBody"
    ]
  },
  "method": "post",
  "pathTemplate": "/v1/tools/depth-pro",
  "parameters": [
    {
      "name": "timeout",
      "in": "query",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "default": 480,
        "title": "Timeout"
      }
    },
    {
      "name": "Authorization",
      "in": "header",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "Use your API key as a Basic token. For example, `Authorization = Basic YOUR_API_KEY`.\n\nTo get your API key, go to https://va.landing.ai/settings/api-key.",
        "title": "Authorization"
      },
      "description": "Use your API key as a Basic token. For example, `Authorization = Basic YOUR_API_KEY`.\n\nTo get your API key, go to https://va.landing.ai/settings/api-key."
    },
    {
      "name": "authorization",
      "in": "header",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "title": "Authorization"
      }
    }
  ],
  "executionParameters": [
    {
      "name": "timeout",
      "in": "query"
    },
    {
      "name": "Authorization",
      "in": "header"
    },
    {
      "name": "authorization",
      "in": "header"
    }
  ],
  "requestBodyContentType": "application/x-www-form-urlencoded",
  "securityRequirements": [],
  "baseUrl": "https://api.va.landing.ai"
}],
  ["text-to-instance-segmentation", {
  "name": "text-to-instance-segmentation",
  "description": "Tool Text To Seg",
  "inputSchema": {
    "type": "object",
    "properties": {
      "timeout": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "default": 480,
        "title": "Timeout"
      },
      "Authorization": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "Use your API key as a Basic token. For example, `Authorization = Basic YOUR_API_KEY`.\n\nTo get your API key, go to https://va.landing.ai/settings/api-key.",
        "title": "Authorization"
      },
      "authorization": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "title": "Authorization"
      },
      "requestBody": {
        "properties": {
          "image": {
            "anyOf": [
              {
                "type": "string",
                "format": "binary"
              },
              {
                "type": "null"
              }
            ],
            "title": "Image"
          },
          "video": {
            "anyOf": [
              {
                "type": "string",
                "format": "binary"
              },
              {
                "type": "null"
              }
            ],
            "title": "Video"
          },
          "prompt": {
            "type": "string",
            "title": "Prompt"
          },
          "model": {
            "type": "string",
            "enum": [
              "florence2sam2"
            ],
            "title": "TextToSegModel"
          },
          "chunkLengthFrames": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "title": "Chunklengthframes"
          },
          "iouThreshold": {
            "anyOf": [
              {
                "type": "number",
                "maximum": 1,
                "minimum": 0.1
              },
              {
                "type": "null"
              }
            ],
            "title": "Iouthreshold"
          },
          "nmsThreshold": {
            "anyOf": [
              {
                "type": "number",
                "maximum": 1,
                "minimum": 0.1
              },
              {
                "type": "null"
              }
            ],
            "title": "Nmsthreshold"
          },
          "jobId": {
            "anyOf": [
              {
                "type": "string",
                "format": "uuid"
              },
              {
                "type": "null"
              }
            ],
            "title": "Jobid"
          }
        },
        "type": "object",
        "required": [
          "prompt",
          "model"
        ],
        "title": "FormData",
        "description": "Request body (content type: application/x-www-form-urlencoded)"
      }
    },
    "required": [
      "requestBody"
    ]
  },
  "method": "post",
  "pathTemplate": "/v1/tools/text-to-instance-segmentation",
  "parameters": [
    {
      "name": "timeout",
      "in": "query",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "default": 480,
        "title": "Timeout"
      }
    },
    {
      "name": "Authorization",
      "in": "header",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "Use your API key as a Basic token. For example, `Authorization = Basic YOUR_API_KEY`.\n\nTo get your API key, go to https://va.landing.ai/settings/api-key.",
        "title": "Authorization"
      },
      "description": "Use your API key as a Basic token. For example, `Authorization = Basic YOUR_API_KEY`.\n\nTo get your API key, go to https://va.landing.ai/settings/api-key."
    },
    {
      "name": "authorization",
      "in": "header",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "title": "Authorization"
      }
    }
  ],
  "executionParameters": [
    {
      "name": "timeout",
      "in": "query"
    },
    {
      "name": "Authorization",
      "in": "header"
    },
    {
      "name": "authorization",
      "in": "header"
    }
  ],
  "requestBodyContentType": "application/x-www-form-urlencoded",
  "securityRequirements": [],
  "baseUrl": "https://api.va.landing.ai"
}],
  ["agentic-document-analysis", {
  "name": "agentic-document-analysis",
  "description": "Send documents to the Agentic Document Extraction API.\n\nThe API parses the documents and returns the extracted data as structured Markdown and JSON.",
  "inputSchema": {
    "type": "object",
    "properties": {
      "pages": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "Which pages to process, separated by comma and starting from 0. For example, to process the first 3 pages, use '0,1,2'. ",
        "title": "Pages"
      },
      "timeout": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "default": 480,
        "title": "Timeout"
      },
      "Authorization": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "Use your API key as a Basic token. For example, `Authorization = Basic YOUR_API_KEY`.\n\nTo get your API key, go to https://va.landing.ai/settings/api-key.",
        "title": "Authorization"
      },
      "authorization": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "title": "Authorization"
      },
      "requestBody": {
        "properties": {
          "image": {
            "anyOf": [
              {
                "type": "string",
                "format": "binary"
              },
              {
                "type": "null"
              }
            ],
            "title": "Image"
          },
          "pdf": {
            "anyOf": [
              {
                "type": "string",
                "format": "binary"
              },
              {
                "type": "null"
              }
            ],
            "title": "Pdf"
          },
          "include_marginalia": {
            "type": "boolean",
            "title": "Include Marginalia",
            "default": true
          },
          "include_metadata_in_markdown": {
            "type": "boolean",
            "title": "Include Metadata In Markdown",
            "default": true
          }
        },
        "type": "object",
        "title": "DocAnalysisRequest",
        "description": "Request body (content type: application/x-www-form-urlencoded)"
      }
    },
    "required": [
      "requestBody"
    ]
  },
  "method": "post",
  "pathTemplate": "/v1/tools/agentic-document-analysis",
  "parameters": [
    {
      "name": "pages",
      "in": "query",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "Which pages to process, separated by comma and starting from 0. For example, to process the first 3 pages, use '0,1,2'. ",
        "title": "Pages"
      },
      "description": "Which pages to process, separated by comma and starting from 0. For example, to process the first 3 pages, use '0,1,2'. "
    },
    {
      "name": "timeout",
      "in": "query",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "default": 480,
        "title": "Timeout"
      }
    },
    {
      "name": "Authorization",
      "in": "header",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "Use your API key as a Basic token. For example, `Authorization = Basic YOUR_API_KEY`.\n\nTo get your API key, go to https://va.landing.ai/settings/api-key.",
        "title": "Authorization"
      },
      "description": "Use your API key as a Basic token. For example, `Authorization = Basic YOUR_API_KEY`.\n\nTo get your API key, go to https://va.landing.ai/settings/api-key."
    },
    {
      "name": "authorization",
      "in": "header",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "title": "Authorization"
      }
    }
  ],
  "executionParameters": [
    {
      "name": "pages",
      "in": "query"
    },
    {
      "name": "timeout",
      "in": "query"
    },
    {
      "name": "Authorization",
      "in": "header"
    },
    {
      "name": "authorization",
      "in": "header"
    }
  ],
  "requestBodyContentType": "application/x-www-form-urlencoded",
  "securityRequirements": [],
  "baseUrl": "https://api.va.landing.ai"
}],
  ["paddle-ocr", {
  "name": "paddle-ocr",
  "description": "Tool Paddle Ocr",
  "inputSchema": {
    "type": "object",
    "properties": {
      "timeout": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "default": 480,
        "title": "Timeout"
      },
      "Authorization": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "Use your API key as a Basic token. For example, `Authorization = Basic YOUR_API_KEY`.\n\nTo get your API key, go to https://va.landing.ai/settings/api-key.",
        "title": "Authorization"
      },
      "authorization": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "title": "Authorization"
      },
      "requestBody": {
        "properties": {
          "image": {
            "anyOf": [
              {
                "type": "string",
                "format": "binary"
              },
              {
                "type": "null"
              }
            ],
            "title": "Image"
          },
          "video": {
            "anyOf": [
              {
                "type": "string",
                "format": "binary"
              },
              {
                "type": "null"
              }
            ],
            "title": "Video"
          }
        },
        "type": "object",
        "title": "BaseMediaRequest",
        "description": "Request body (content type: application/x-www-form-urlencoded)"
      }
    },
    "required": [
      "requestBody"
    ]
  },
  "method": "post",
  "pathTemplate": "/v1/tools/paddle-ocr",
  "parameters": [
    {
      "name": "timeout",
      "in": "query",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "default": 480,
        "title": "Timeout"
      }
    },
    {
      "name": "Authorization",
      "in": "header",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "Use your API key as a Basic token. For example, `Authorization = Basic YOUR_API_KEY`.\n\nTo get your API key, go to https://va.landing.ai/settings/api-key.",
        "title": "Authorization"
      },
      "description": "Use your API key as a Basic token. For example, `Authorization = Basic YOUR_API_KEY`.\n\nTo get your API key, go to https://va.landing.ai/settings/api-key."
    },
    {
      "name": "authorization",
      "in": "header",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "title": "Authorization"
      }
    }
  ],
  "executionParameters": [
    {
      "name": "timeout",
      "in": "query"
    },
    {
      "name": "Authorization",
      "in": "header"
    },
    {
      "name": "authorization",
      "in": "header"
    }
  ],
  "requestBodyContentType": "application/x-www-form-urlencoded",
  "securityRequirements": [],
  "baseUrl": "https://api.va.landing.ai"
}],
  ["activity-recognition", {
  "name": "activity-recognition",
  "description": "Performs activity recognition\n\nArgs:\n    video (UploadFile): The video file to analyze.\n    prompt (str): The prompt to guide activity recognition.\n    specificity (Specificity, optional): Detail level in the response (low, medium, high, max).\n    with_audio (bool, optional): Whether to process audio as well. Defaults to False.",
  "inputSchema": {
    "type": "object",
    "properties": {
      "timeout": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "default": 480,
        "title": "Timeout"
      },
      "Authorization": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "Use your API key as a Basic token. For example, `Authorization = Basic YOUR_API_KEY`.\n\nTo get your API key, go to https://va.landing.ai/settings/api-key.",
        "title": "Authorization"
      },
      "authorization": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "title": "Authorization"
      },
      "requestBody": {
        "properties": {
          "video": {
            "type": "string",
            "format": "binary",
            "title": "Video"
          },
          "prompt": {
            "type": "string",
            "title": "Prompt"
          },
          "specificity": {
            "default": "max",
            "type": "string",
            "enum": [
              "low",
              "medium",
              "high",
              "max"
            ],
            "title": "Specificity"
          },
          "with_audio": {
            "type": "boolean",
            "title": "With Audio",
            "default": false
          }
        },
        "type": "object",
        "required": [
          "video",
          "prompt"
        ],
        "title": "Body_tool_activity_recognition_v1_tools_activity_recognition_post",
        "description": "Request body (content type: multipart/form-data)"
      }
    },
    "required": [
      "requestBody"
    ]
  },
  "method": "post",
  "pathTemplate": "/v1/tools/activity-recognition",
  "parameters": [
    {
      "name": "timeout",
      "in": "query",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "default": 480,
        "title": "Timeout"
      }
    },
    {
      "name": "Authorization",
      "in": "header",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "Use your API key as a Basic token. For example, `Authorization = Basic YOUR_API_KEY`.\n\nTo get your API key, go to https://va.landing.ai/settings/api-key.",
        "title": "Authorization"
      },
      "description": "Use your API key as a Basic token. For example, `Authorization = Basic YOUR_API_KEY`.\n\nTo get your API key, go to https://va.landing.ai/settings/api-key."
    },
    {
      "name": "authorization",
      "in": "header",
      "required": false,
      "schema": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "title": "Authorization"
      }
    }
  ],
  "executionParameters": [
    {
      "name": "timeout",
      "in": "query"
    },
    {
      "name": "Authorization",
      "in": "header"
    },
    {
      "name": "authorization",
      "in": "header"
    }
  ],
  "requestBodyContentType": "multipart/form-data",
  "securityRequirements": [],
  "baseUrl": "https://api.va.landing.ai"
}]
]);
